default: &default
  adapter: mysql2
  database: myarticles
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: disalles
  password: 33838449
  timeout: 5000
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: myarticles

test:
  <<: *default
  database: myarticles

production:
  <<: *default
  database: myarticles
